# <arenaName>:
#   enable: false
#   waitingRoom: <world>;<x>;<y>;<z>;<yaw>;<pitch>
#   spawns:
#   - <world>;<x>;<y>;<z>;<yaw>;<pitch>
#   - <world>;<x>;<y>;<z>;<yaw>;<pitch>
#   - <world>;<x>;<y>;<z>;<yaw>;<pitch>
#   ...
#   bounds:
#     bound:
#       high: <world>;<x>;<y>;<z>;<yaw>;<pitch>
#       low: <world>;<x>;<y>;<z>;<yaw>;<pitch>
#     spec:
#       high: <world>;<x>;<y>;<z>;<yaw>;<pitch>
#       low: <world>;<x>;<y>;<z>;<yaw>;<pitch>
#   min_player: 4
#   max_player: 8
#   displayName: <DisplayName>
#   author: <AuthorID>
#   description: <Description>